import { MapPin, Scale } from 'lucide-react';
import { FeasibilityReport, SceneSpec } from '@/lib/schemas';

export function ComparisonMatrix({ reports, sceneSpec }: { reports: FeasibilityReport[]; sceneSpec: SceneSpec }) {
  const recommendation = reports[0];
  return (
    <div className="space-y-5">
      {recommendation && <div className="rounded-2xl border border-amber-500/35 bg-amber-950/15 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-amber-400">Producer&apos;s first look</p><h2 className="mt-2 font-serif text-3xl text-ash-50">Start with {recommendation.candidate_name}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-ash-300">The highest-scoring candidate based on the evidence currently found. This is a research recommendation, not official permission.</p></div><MapPin className="h-7 w-7 shrink-0 text-amber-400" aria-hidden="true" /></div></div>}
      <div className="glass-panel overflow-hidden rounded-2xl border border-ink-800"><div className="border-b border-ink-800 px-5 py-4"><div className="flex items-center gap-3"><Scale className="h-5 w-5 text-teal-400" /><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-teal-400">Decision matrix</p><h2 className="mt-1 font-serif text-2xl text-ash-50">What the score is made of</h2></div></div></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><caption className="sr-only">Production feasibility scores by candidate location</caption><thead className="bg-ink-900/70 font-mono text-[10px] uppercase tracking-[0.14em] text-ash-500"><tr><th className="px-5 py-4">Candidate</th><th className="px-5 py-4">Visual <span className="text-ash-600">/30</span></th><th className="px-5 py-4">Permit <span className="text-ash-600">/30</span></th><th className="px-5 py-4">Access <span className="text-ash-600">/20</span></th><th className="px-5 py-4">Risk <span className="text-ash-600">/20</span></th><th className="px-5 py-4">Total</th></tr></thead><tbody className="divide-y divide-ink-800">{reports.map((report, index) => <tr key={report.candidate_id} className="text-ash-200"><td className="px-5 py-4 font-medium text-ash-50">{index === 0 && <span className="mr-2 text-amber-400">★</span>}{report.candidate_name}</td><td className="px-5 py-4 font-mono">{report.score_breakdown.visual_match}</td><td className="px-5 py-4 font-mono">{report.score_breakdown.permit_evidence}</td><td className="px-5 py-4 font-mono">{report.score_breakdown.logistics_access}</td><td className="px-5 py-4 font-mono">{report.score_breakdown.risk_profile}</td><td className="px-5 py-4 font-mono font-semibold text-amber-300">{report.feasibility_score}</td></tr>)}</tbody></table></div><div className="border-t border-ink-800 px-5 py-4 text-xs leading-5 text-ash-400">Weights: visual match 30%, permit evidence 30%, access/logistics 20%, risk profile 20%. Scene mode: <span className="text-ash-200">{sceneSpec.time_of_day}</span> · <span className="text-ash-200">{sceneSpec.setting_type.replaceAll('_', ' ')}</span>.</div></div>
    </div>
  );
}
